name: Build Packages

on:
  push:
    tags:
      - "*"
    branches:
      - lua
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        sdk:
          - openwrt-21.02
          - openwrt-22.03

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read PKG_VERSION from Makefile
        id: version
        run: |
          RAW=$(grep "^PKG_VERSION:=" alist/Makefile | sed 's/PKG_VERSION:=//')
          echo "alist_version_raw=$RAW" >> $GITHUB_OUTPUT
          echo "alist_version=v$RAW" >> $GITHUB_OUTPUT

      - name: Build
        uses: sbwml/openwrt-gh-action-sdk@go1.26
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-alist
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ matrix.sdk }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Create compress files
        run: |
          tar -zcvf ${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz -C bin/packages/${{ matrix.arch }}/ packages_ci

      - name: Create tag
        run: |
          git tag ${{ steps.version.outputs.alist_version }}
          git push origin ${{ steps.version.outputs.alist_version }}

      - name: Upload packages
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.alist_version }}
          name: lua ${{ steps.version.outputs.alist_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "${{ matrix.sdk }}-${{ matrix.arch }}.tar.gz"
